import { describe, expect, it } from "vitest";
import { DIST_ACTIVE_COUNTS, DIST_ACTIVE_N, DIST_COUNTS, DIST_MIN, DIST_N } from "@/lib/distribution-data";

// Locks the invariants of the baked histogram (lib/distribution-data.json,
// regenerated by distribution-runner.ts) that DistributionPanel relies on.
describe("distribution data", () => {
  it("covers ratings DIST_MIN..99, one bucket per rating", () => {
    expect(DIST_MIN).toBe(50);
    expect(DIST_COUNTS).toHaveLength(100 - DIST_MIN);
    expect(DIST_ACTIVE_COUNTS).toHaveLength(100 - DIST_MIN);
  });

  it("counts sum to their populations", () => {
    const sum = (a: number[]) => a.reduce((s, c) => s + c, 0);
    expect(sum(DIST_COUNTS)).toBe(DIST_N);
    expect(sum(DIST_ACTIVE_COUNTS)).toBe(DIST_ACTIVE_N);
  });

  it("active devs are a subset of the full sample, bucket by bucket", () => {
    expect(DIST_ACTIVE_N).toBeLessThanOrEqual(DIST_N);
    DIST_ACTIVE_COUNTS.forEach((c, i) => expect(c).toBeLessThanOrEqual(DIST_COUNTS[i]));
  });

  it("has a real sample behind it (panel divides by these)", () => {
    expect(DIST_N).toBeGreaterThan(0);
    expect(DIST_ACTIVE_N).toBeGreaterThan(0);
    expect(Math.max(...DIST_COUNTS)).toBeGreaterThan(0);
  });
});
