import { chromium } from "playwright";
const b=await chromium.launch();
const p=await (await b.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:3})).newPage();
await p.goto("http://localhost:4000/u/Mawsis",{waitUntil:"networkidle"}).catch(()=>{});
await p.waitForTimeout(3000);
const share=p.getByRole("button",{name:/SHARE MY CARD/i}).first();
const box=await share.boundingBox();
const dl=p.getByRole("button",{name:/Download your card/i}).first();
await dl.hover().catch(()=>{});
await p.waitForTimeout(300);
await p.screenshot({path:"/private/tmp/claude-501/-Users-mac-Workshop-Personal-gitfut/2227b677-a267-449b-8d82-867bc03f52f4/scratchpad/shots2/S3-dl-hover.png", clip:{x:(box?box.x-30:480),y:(box?box.y+150:600),height:130,width:(box?box.width+60:380)}});
console.log("done");
await b.close();
